migrate((app) => {
  const collections = [
    {
      "fields": [
        {
          "autogeneratePattern": "[a-z0-9]{15}",
          "hidden": false,
          "id": "text3208210256",
          "max": 15,
          "min": 15,
          "name": "id",
          "pattern": "^[a-z0-9]+$",
          "presentable": false,
          "primaryKey": true,
          "required": true,
          "system": true,
          "type": "text"
        },
        {
          "autogeneratePattern": "",
          "hidden": false,
          "id": "text2363381545",
          "max": 0,
          "min": 0,
          "name": "type",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": true,
          "system": false,
          "type": "text"
        },
        {
          "autogeneratePattern": "",
          "hidden": false,
          "id": "text1337919823",
          "max": 0,
          "min": 0,
          "name": "company",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": false,
          "system": false,
          "type": "text"
        },
        {
          "autogeneratePattern": "",
          "hidden": false,
          "id": "text1120422229",
          "max": 0,
          "min": 0,
          "name": "reservation",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": false,
          "system": false,
          "type": "text"
        },
        {
          "hidden": false,
          "id": "number405181692",
          "max": null,
          "min": null,
          "name": "cost",
          "onlyInt": false,
          "presentable": false,
          "required": false,
          "system": false,
          "type": "number"
        },
        {
          "autogeneratePattern": "",
          "hidden": false,
          "id": "text3105530224",
          "max": 0,
          "min": 0,
          "name": "from",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": false,
          "system": false,
          "type": "text"
        },
        {
          "autogeneratePattern": "",
          "hidden": false,
          "id": "text3616002756",
          "max": 0,
          "min": 0,
          "name": "to",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": false,
          "system": false,
          "type": "text"
        },
        {
          "hidden": false,
          "id": "date2912961383",
          "max": "",
          "min": "",
          "name": "from_at",
          "presentable": false,
          "required": false,
          "system": false,
          "type": "date"
        },
        {
          "hidden": false,
          "id": "date3847999497",
          "max": "",
          "min": "",
          "name": "to_at",
          "presentable": false,
          "required": false,
          "system": false,
          "type": "date"
        },
        {
          "cascadeDelete": true,
          "collectionId": "pbc_1973380996",
          "hidden": false,
          "id": "relation1439645945",
          "maxSelect": 1,
          "minSelect": 0,
          "name": "adventure_id",
          "presentable": false,
          "required": false,
          "system": false,
          "type": "relation"
        },
        {
          "hidden": false,
          "id": "autodate2990389176",
          "name": "created",
          "onCreate": true,
          "onUpdate": false,
          "presentable": false,
          "system": false,
          "type": "autodate"
        },
        {
          "hidden": false,
          "id": "autodate3332085495",
          "name": "updated",
          "onCreate": true,
          "onUpdate": true,
          "presentable": false,
          "system": false,
          "type": "autodate"
        }
      ],
      "id": "pbc_815058846",
      "indexes": [],
      "name": "transportations",
      "system": false,
      "type": "base",
      "createRule": "adventure_id.user_id.id = @request.auth.id",
      "deleteRule": "adventure_id.user_id.id = @request.auth.id",
      "listRule": "adventure_id.user_id.id = @request.auth.id",
      "updateRule": "adventure_id.user_id.id = @request.auth.id",
      "viewRule": "adventure_id.user_id.id = @request.auth.id"
    },
    {
      "fields": [
        {
          "autogeneratePattern": "[a-z0-9]{15}",
          "hidden": false,
          "id": "text3208210256",
          "max": 15,
          "min": 15,
          "name": "id",
          "pattern": "^[a-z0-9]+$",
          "presentable": false,
          "primaryKey": true,
          "required": true,
          "system": true,
          "type": "text"
        },
        {
          "autogeneratePattern": "",
          "hidden": false,
          "id": "text1587448267",
          "max": 0,
          "min": 0,
          "name": "location",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": false,
          "system": false,
          "type": "text"
        },
        {
          "autogeneratePattern": "",
          "hidden": false,
          "id": "text1337919823",
          "max": 0,
          "min": 0,
          "name": "company",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": false,
          "system": false,
          "type": "text"
        },
        {
          "autogeneratePattern": "",
          "hidden": false,
          "id": "text1120422229",
          "max": 0,
          "min": 0,
          "name": "reservation",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": false,
          "system": false,
          "type": "text"
        },
        {
          "hidden": false,
          "id": "text405181692",
          "max": null,
          "min": null,
          "name": "cost",
          "onlyInt": false,
          "presentable": false,
          "required": false,
          "system": false,
          "type": "number"
        },
        {
          "hidden": false,
          "id": "date2912961383",
          "max": "",
          "min": "",
          "name": "from_at",
          "presentable": false,
          "required": false,
          "system": false,
          "type": "date"
        },
        {
          "hidden": false,
          "id": "date3847999497",
          "max": "",
          "min": "",
          "name": "to_at",
          "presentable": false,
          "required": false,
          "system": false,
          "type": "date"
        },
        {
          "cascadeDelete": true,
          "collectionId": "pbc_1973380996",
          "hidden": false,
          "id": "relation1251414960",
          "maxSelect": 1,
          "minSelect": 0,
          "name": "adventure_id",
          "presentable": false,
          "required": false,
          "system": false,
          "type": "relation"
        },
        {
          "hidden": false,
          "id": "autodate2990389176",
          "name": "created",
          "onCreate": true,
          "onUpdate": false,
          "presentable": false,
          "system": false,
          "type": "autodate"
        },
        {
          "hidden": false,
          "id": "autodate3332085495",
          "name": "updated",
          "onCreate": true,
          "onUpdate": true,
          "presentable": false,
          "system": false,
          "type": "autodate"
        }
      ],
      "id": "pbc_2155244508",
      "indexes": [],
      "name": "lodgings",
      "system": false,
      "type": "base",
      "createRule": "adventure_id.user_id.id = @request.auth.id",
      "deleteRule": "adventure_id.user_id.id = @request.auth.id",
      "listRule": "adventure_id.user_id.id = @request.auth.id",
      "updateRule": "adventure_id.user_id.id = @request.auth.id",
      "viewRule": "adventure_id.user_id.id = @request.auth.id"
    },
    {
      "fields": [
        {
          "autogeneratePattern": "[a-z0-9]{15}",
          "hidden": false,
          "id": "text3208210256",
          "max": 15,
          "min": 15,
          "name": "id",
          "pattern": "^[a-z0-9]+$",
          "presentable": false,
          "primaryKey": true,
          "required": true,
          "system": true,
          "type": "text"
        },
        {
          "autogeneratePattern": "",
          "hidden": false,
          "id": "text1579384326",
          "max": 0,
          "min": 0,
          "name": "name",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": false,
          "system": false,
          "type": "text"
        },
        {
          "autogeneratePattern": "",
          "hidden": false,
          "id": "text1587448267",
          "max": 0,
          "min": 0,
          "name": "location",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": false,
          "system": false,
          "type": "text"
        },
        {
          "hidden": false,
          "id": "number405181692",
          "max": null,
          "min": null,
          "name": "cost",
          "onlyInt": false,
          "presentable": false,
          "required": false,
          "system": false,
          "type": "number"
        },
        {
          "hidden": false,
          "id": "date1784151356",
          "max": "",
          "min": "",
          "name": "at",
          "presentable": false,
          "required": false,
          "system": false,
          "type": "date"
        },
        {
          "cascadeDelete": true,
          "collectionId": "pbc_1973380996",
          "hidden": false,
          "id": "relation1439645945",
          "maxSelect": 1,
          "minSelect": 0,
          "name": "adventure_id",
          "presentable": false,
          "required": false,
          "system": false,
          "type": "relation"
        },
        {
          "hidden": false,
          "id": "autodate2990389176",
          "name": "created",
          "onCreate": true,
          "onUpdate": false,
          "presentable": false,
          "system": false,
          "type": "autodate"
        },
        {
          "hidden": false,
          "id": "autodate3332085495",
          "name": "updated",
          "onCreate": true,
          "onUpdate": true,
          "presentable": false,
          "system": false,
          "type": "autodate"
        }
      ],
      "id": "pbc_1262591861",
      "indexes": [],
      "name": "activities",
      "system": false,
      "type": "base",
      "createRule": "adventure_id.user_id.id = @request.auth.id",
      "deleteRule": "adventure_id.user_id.id = @request.auth.id",
      "listRule": "adventure_id.user_id.id = @request.auth.id",
      "updateRule": "adventure_id.user_id.id = @request.auth.id",
      "viewRule": "adventure_id.user_id.id = @request.auth.id"
    }
  ]
  collections.map((item) => app.save(new Collection(item)))
}, (_) => { })