version: '3'

services:
  back:
    restart: unless-stopped
    image: alpine
    command: "/app/pb/pocketbase serve --dev --http 0.0.0.0:8090"
    volumes:
      - ./back:/app/pb
    working_dir: /app/pb
    environment:
      - HOME=/app/pb
      - PB_ADMIN_EMAIL=test@test.com
      - PB_ADMIN_PASSWORD=12345678
      - TRUSTED_HEADER_EMAIL=X-Auth-Request-Email

    # build: .
    ports:
      - 8090:8090
